name: hashcodes
description: A starting point for Dart libraries or applications.
version: 2.0.0
homepage: https://github.com/CaiJingLong/dart_hashcodes
publish_to: https://pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
