name: hashcodes
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/CaiJingLong/dart_hashcodes

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
